/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Homework = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'completed' : IDL.Bool,
  'dueDate' : Time,
  'notes' : IDL.Opt(IDL.Text),
});
export const Day = IDL.Variant({
  'Saturday' : IDL.Null,
  'Thursday' : IDL.Null,
  'Sunday' : IDL.Null,
  'Tuesday' : IDL.Null,
  'Friday' : IDL.Null,
  'Wednesday' : IDL.Null,
  'Monday' : IDL.Null,
});
export const TimeSlot = IDL.Record({
  'endHour' : IDL.Nat,
  'endMinute' : IDL.Nat,
  'startMinute' : IDL.Nat,
  'startHour' : IDL.Nat,
});
export const TimetableEntry = IDL.Record({
  'id' : IDL.Nat,
  'day' : Day,
  'startTime' : TimeSlot,
  'subject' : IDL.Text,
  'endTime' : TimeSlot,
  'location' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const QuizProgress = IDL.Record({
  'attemptsCount' : IDL.Nat,
  'bestScore' : IDL.Nat,
  'lastScore' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addHomework' : IDL.Func([Homework], [IDL.Nat], []),
  'addTimetableEntry' : IDL.Func([TimetableEntry], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteHomework' : IDL.Func([IDL.Nat], [], []),
  'deleteTimetableEntry' : IDL.Func([IDL.Nat], [], []),
  'getAllHomework' : IDL.Func([], [IDL.Vec(Homework)], ['query']),
  'getAllTimetableEntries' : IDL.Func([], [IDL.Vec(TimetableEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getQuizProgress' : IDL.Func([], [IDL.Opt(QuizProgress)], ['query']),
  'getTimetableEntriesByDay' : IDL.Func(
      [Day],
      [IDL.Vec(TimetableEntry)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveQuizProgress' : IDL.Func([QuizProgress], [], []),
  'updateHomework' : IDL.Func([IDL.Nat, Homework], [], []),
  'updateTimetableEntry' : IDL.Func([IDL.Nat, TimetableEntry], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Homework = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'completed' : IDL.Bool,
    'dueDate' : Time,
    'notes' : IDL.Opt(IDL.Text),
  });
  const Day = IDL.Variant({
    'Saturday' : IDL.Null,
    'Thursday' : IDL.Null,
    'Sunday' : IDL.Null,
    'Tuesday' : IDL.Null,
    'Friday' : IDL.Null,
    'Wednesday' : IDL.Null,
    'Monday' : IDL.Null,
  });
  const TimeSlot = IDL.Record({
    'endHour' : IDL.Nat,
    'endMinute' : IDL.Nat,
    'startMinute' : IDL.Nat,
    'startHour' : IDL.Nat,
  });
  const TimetableEntry = IDL.Record({
    'id' : IDL.Nat,
    'day' : Day,
    'startTime' : TimeSlot,
    'subject' : IDL.Text,
    'endTime' : TimeSlot,
    'location' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const QuizProgress = IDL.Record({
    'attemptsCount' : IDL.Nat,
    'bestScore' : IDL.Nat,
    'lastScore' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addHomework' : IDL.Func([Homework], [IDL.Nat], []),
    'addTimetableEntry' : IDL.Func([TimetableEntry], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteHomework' : IDL.Func([IDL.Nat], [], []),
    'deleteTimetableEntry' : IDL.Func([IDL.Nat], [], []),
    'getAllHomework' : IDL.Func([], [IDL.Vec(Homework)], ['query']),
    'getAllTimetableEntries' : IDL.Func(
        [],
        [IDL.Vec(TimetableEntry)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getQuizProgress' : IDL.Func([], [IDL.Opt(QuizProgress)], ['query']),
    'getTimetableEntriesByDay' : IDL.Func(
        [Day],
        [IDL.Vec(TimetableEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveQuizProgress' : IDL.Func([QuizProgress], [], []),
    'updateHomework' : IDL.Func([IDL.Nat, Homework], [], []),
    'updateTimetableEntry' : IDL.Func([IDL.Nat, TimetableEntry], [], []),
  });
};

export const init = ({ IDL }) => { return []; };