/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface QuizProgress {
    attemptsCount: bigint;
    bestScore: bigint;
    lastScore: bigint;
}
export interface TimeSlot {
    endHour: bigint;
    endMinute: bigint;
    startMinute: bigint;
    startHour: bigint;
}
export type Time = bigint;
export interface TimetableEntry {
    id: bigint;
    day: Day;
    startTime: TimeSlot;
    subject: string;
    endTime: TimeSlot;
    location?: string;
}
export interface Homework {
    id: bigint;
    title: string;
    subject: string;
    completed: boolean;
    dueDate: Time;
    notes?: string;
}
export interface UserProfile {
    name: string;
}
export enum Day {
    Saturday = "Saturday",
    Thursday = "Thursday",
    Sunday = "Sunday",
    Tuesday = "Tuesday",
    Friday = "Friday",
    Wednesday = "Wednesday",
    Monday = "Monday"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addHomework(homework: Homework): Promise<bigint>;
    addTimetableEntry(entry: TimetableEntry): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteHomework(id: bigint): Promise<void>;
    deleteTimetableEntry(id: bigint): Promise<void>;
    getAllHomework(): Promise<Array<Homework>>;
    getAllTimetableEntries(): Promise<Array<TimetableEntry>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getQuizProgress(): Promise<QuizProgress | null>;
    getTimetableEntriesByDay(day: Day): Promise<Array<TimetableEntry>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveQuizProgress(progress: QuizProgress): Promise<void>;
    updateHomework(id: bigint, updatedHomework: Homework): Promise<void>;
    updateTimetableEntry(id: bigint, updatedEntry: TimetableEntry): Promise<void>;
}
import type { Day as _Day, Homework as _Homework, QuizProgress as _QuizProgress, Time as _Time, TimeSlot as _TimeSlot, TimetableEntry as _TimetableEntry, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addHomework(arg0: Homework): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addHomework(to_candid_Homework_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHomework(to_candid_Homework_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTimetableEntry(arg0: TimetableEntry): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTimetableEntry(to_candid_TimetableEntry_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTimetableEntry(to_candid_TimetableEntry_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteHomework(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHomework(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHomework(arg0);
            return result;
        }
    }
    async deleteTimetableEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTimetableEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTimetableEntry(arg0);
            return result;
        }
    }
    async getAllHomework(): Promise<Array<Homework>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHomework();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHomework();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTimetableEntries(): Promise<Array<TimetableEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTimetableEntries();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTimetableEntries();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuizProgress(): Promise<QuizProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizProgress();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizProgress();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTimetableEntriesByDay(arg0: Day): Promise<Array<TimetableEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTimetableEntriesByDay(to_candid_Day_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTimetableEntriesByDay(to_candid_Day_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveQuizProgress(arg0: QuizProgress): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveQuizProgress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveQuizProgress(arg0);
            return result;
        }
    }
    async updateHomework(arg0: bigint, arg1: Homework): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHomework(arg0, to_candid_Homework_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHomework(arg0, to_candid_Homework_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTimetableEntry(arg0: bigint, arg1: TimetableEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTimetableEntry(arg0, to_candid_TimetableEntry_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTimetableEntry(arg0, to_candid_TimetableEntry_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Day_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Day): Day {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Homework_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Homework): Homework {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_TimetableEntry_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimetableEntry): TimetableEntry {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_QuizProgress]): QuizProgress | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    subject: string;
    completed: boolean;
    dueDate: _Time;
    notes: [] | [string];
}): {
    id: bigint;
    title: string;
    subject: string;
    completed: boolean;
    dueDate: Time;
    notes?: string;
} {
    return {
        id: value.id,
        title: value.title,
        subject: value.subject,
        completed: value.completed,
        dueDate: value.dueDate,
        notes: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.notes))
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    day: _Day;
    startTime: _TimeSlot;
    subject: string;
    endTime: _TimeSlot;
    location: [] | [string];
}): {
    id: bigint;
    day: Day;
    startTime: TimeSlot;
    subject: string;
    endTime: TimeSlot;
    location?: string;
} {
    return {
        id: value.id,
        day: from_candid_Day_n16(_uploadFile, _downloadFile, value.day),
        startTime: value.startTime,
        subject: value.subject,
        endTime: value.endTime,
        location: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.location))
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Saturday: null;
} | {
    Thursday: null;
} | {
    Sunday: null;
} | {
    Tuesday: null;
} | {
    Friday: null;
} | {
    Wednesday: null;
} | {
    Monday: null;
}): Day {
    return "Saturday" in value ? Day.Saturday : "Thursday" in value ? Day.Thursday : "Sunday" in value ? Day.Sunday : "Tuesday" in value ? Day.Tuesday : "Friday" in value ? Day.Friday : "Wednesday" in value ? Day.Wednesday : "Monday" in value ? Day.Monday : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TimetableEntry>): Array<TimetableEntry> {
    return value.map((x)=>from_candid_TimetableEntry_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Homework>): Array<Homework> {
    return value.map((x)=>from_candid_Homework_n10(_uploadFile, _downloadFile, x));
}
function to_candid_Day_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Day): _Day {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Homework_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Homework): _Homework {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_TimetableEntry_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimetableEntry): _TimetableEntry {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    subject: string;
    completed: boolean;
    dueDate: Time;
    notes?: string;
}): {
    id: bigint;
    title: string;
    subject: string;
    completed: boolean;
    dueDate: _Time;
    notes: [] | [string];
} {
    return {
        id: value.id,
        title: value.title,
        subject: value.subject,
        completed: value.completed,
        dueDate: value.dueDate,
        notes: value.notes ? candid_some(value.notes) : candid_none()
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    day: Day;
    startTime: TimeSlot;
    subject: string;
    endTime: TimeSlot;
    location?: string;
}): {
    id: bigint;
    day: _Day;
    startTime: _TimeSlot;
    subject: string;
    endTime: _TimeSlot;
    location: [] | [string];
} {
    return {
        id: value.id,
        day: to_candid_Day_n5(_uploadFile, _downloadFile, value.day),
        startTime: value.startTime,
        subject: value.subject,
        endTime: value.endTime,
        location: value.location ? candid_some(value.location) : candid_none()
    };
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Day): {
    Saturday: null;
} | {
    Thursday: null;
} | {
    Sunday: null;
} | {
    Tuesday: null;
} | {
    Friday: null;
} | {
    Wednesday: null;
} | {
    Monday: null;
} {
    return value == Day.Saturday ? {
        Saturday: null
    } : value == Day.Thursday ? {
        Thursday: null
    } : value == Day.Sunday ? {
        Sunday: null
    } : value == Day.Tuesday ? {
        Tuesday: null
    } : value == Day.Friday ? {
        Friday: null
    } : value == Day.Wednesday ? {
        Wednesday: null
    } : value == Day.Monday ? {
        Monday: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
